objects/WebService_Info__mdt/WebService_Info__mdt.object-meta.xml
<CustomObject>
    <label>Web Service Info</label>
    <pluralLabel>Web Services Info</pluralLabel>
</CustomObject>

objects/WebService_Info__mdt/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/WebService_Info__mdt/fields/webServiceTokens__c.field-meta.xml
<CustomField>
    <fullName>webServiceTokens__c</fullName>
    <description>auth info</description>
    <label>Web Service Tokens</label>
    <referenceTo>webService_tokens__mdt</referenceTo>
    <relationshipLabel>Web Services Info</relationshipLabel>
    <relationshipName>Web_Services_Info</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

objects/webService_tokens__mdt/webService_tokens__mdt.object-meta.xml
<CustomObject>
    <description>Store oauth info, tokens, cert name, etc</description>
    <label>Web Service Tokens</label>
    <pluralLabel>Web Services Tokens</pluralLabel>
</CustomObject>

objects/webService_tokens__mdt/fields/sf_certificate_name__c.field-meta.xml
<CustomField>
    <fullName>sf_certificate_name__c</fullName>
    <description>Nombre del certificado que se utilizará para realizar la llamada. Los certificados se gestionan en Setups &gt; Security &gt; Certificate and Key Management</description>
    <label>sf certificate name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/Service_Helper_CLS.cls
/****************************************************************************************************
Desarrollado por:   VASS
Proyecto:           -
Descripción:        Clase auxiliar con métodos de ayuda a todos los callouts

Cambios (Versiones)
-----------------------------------------------------------------------------------------------------
No.     Fecha           Autor                   Descripción
-----   ----------      --------------------    -----------------------------------------------------
1.0     2019-10-03		Santiago Cividanes		Creación de la Clase.                                       
*/
public class Service_Helper_CLS {

	public static HttpRequest setCommonHeaders(HttpRequest httpRequest, String mdtName, Map<String, String> urlParams) {
	  List<WebService_Info__mdt> lst_wsInfo = [
		  SELECT EndPoint__c, Method__c, Content_Type__c,webServiceTokens__c,webServiceTokens__r.client_id__c, webServiceTokens__r.client_secret__c
		  , webServiceTokens__r.sf_certificate_name__c
		  FROM WebService_Info__mdt
		  WHERE DeveloperName = :mdtName
	  ];
  
	  httpRequest.setEndpoint(formatUrl(lst_wsInfo.get(0).EndPoint__c, urlParams));
	  
	  httpRequest.setMethod(lst_wsInfo.get(0).Method__c);
	  // httpRequest.setClientCertificateName('db_hd_salesforce');
	  httpRequest.setTimeout(120000);
	  if(lst_wsInfo.get(0).webServiceTokens__c != null){
		if(lst_wsInfo.get(0).webServiceTokens__r.sf_certificate_name__c!= null)httpRequest.setClientCertificateName(lst_wsInfo.get(0).webServiceTokens__r.sf_certificate_name__c);
		httpRequest.setHeader('client_secret', lst_wsInfo.get(0).webServiceTokens__r.client_secret__c);
		httpRequest.setHeader('client_id', lst_wsInfo.get(0).webServiceTokens__r.client_id__c);
	  }
  
  
	  if(lst_wsInfo.get(0).Content_Type__c != null)httpRequest.setHeader('content-type', lst_wsInfo.get(0).Content_Type__c);
  
	  return httpRequest;
	}
  
	public static String urlEncode(Map<String, String> vals) {
	  String result = '';
	  for (String thisKey : vals.keySet()) {
		result += EncodingUtil.urlEncode(thisKey, 'UTF-8') + '=' + EncodingUtil.urlEncode(vals.get(thisKey), 'UTF-8') + '&';
	  }
	  return result.removeEnd('&');
	}
  
	private static String formatUrl(String url, Map<String, String> urlParams){
	  
	  if(urlParams == null) return url;
	  String retUrl = url;
	  for(String key : urlParams.keySet()){
		  System.debug('key ' + key);
		  String formattedKey = '{' + key.trim() + '}';
		  System.debug('formattedKey ' + formattedKey + ' retUrl ' + retUrl);
		  System.debug('contains ' + retUrl.contains(formattedKey));
		  if(retUrl.contains(formattedKey)){
			  System.debug('formattedKey ' + urlParams.get(key));
			  retUrl = retUrl.replace(formattedKey, urlParams.get(key));
		  }
	  }
	  system.debug('url ' + retUrl);
	  return retUrl;
	}
  
  }